### ISSUE TITLE
Love you man

### ISSUE THREAD

**Issue by llgc80** [atinesh-s/Coursera-Machine-Learning-Stanford#1]
Thanks for all of these. 

Question, what other online course do you reccomend?

Greetings from Argentina.

**Comment by atinesh229** [comment]
Thanks Bro, But please try to do all the Quizzes and Programming Assignments by yourself otherwise you'll not be able to grasp the intuition. About the other MOOC's it depends on your current profession.

**Comment by llgc80** [comment]
I am doing bro! I've just doing all the quizzes again to get 5 of 5 in every one and have a complete quizz file to me... About my profession I'm an acoounter with passion with al stats things, but this also it´s very very interesting to me...

**Comment by atinesh229** [comment]
Good Luck

**Comment by llgc80** [comment]
You are the one bro, really, thank you
