### ISSUE TITLE
Vectorization of matrix

### ISSUE THREAD

**Issue by mayank9721** [atinesh-s/Coursera-Machine-Learning-Stanford#10]
X_norm = (X - (t * mu)) ./ (t * sigma);  %vectorized

In above Octave code, if X is 97 x 3 matrix then will it implicitly get converted to column vector?

**Comment by manojdintakurti** [comment]
yes it will implicitly chages its shape

**Comment by atinesh-s** [comment]
@mayank9721 If your issue is resolved then please close the issue
