### ISSUE TITLE
Issue in running GradientDescent

### ISSUE THREAD

**Issue by somrajmaji** [atinesh-s/Coursera-Machine-Learning-Stanford#16]
Hi, Still getting error,

>> gradientDescent
Not enough input arguments.

Error in gradientDescent (line 7)
m = length(y); % number of training examples

**Comment by saran-surya** [comment]
It is because you did not pass the values to the function, try passing some values to them 👍🏻

**Comment by Twowit2woo** [comment]
How do you do this? I get ‘not enough input arguments’ every time

**Comment by atinesh-s** [comment]
I don't know how you are running `gradientDescent()` function in [gradientDescent.m](https://github.com/atinesh-s/Coursera-Machine-Learning-Stanford/blob/master/Week%202/Programming%20Assignment/machine-learning-ex1/ex1/gradientDescent.m).

You have to run the [ex1.m](https://github.com/atinesh-s/Coursera-Machine-Learning-Stanford/blob/master/Week%202/Programming%20Assignment/machine-learning-ex1/ex1/ex1.m) script which makes a function call to `gradientDescent()` with appropriate parameters.

Feel free to reopen the issue if you still have the doubt.
