### ISSUE TITLE
No fourth question in Quiz 11.pdf week 6

### ISSUE THREAD

**Issue by CherprangA** [atinesh-s/Coursera-Machine-Learning-Stanford#19]
Quiz 11.pdf in week 6 contains 1,2,3 and 5 but no 4th question.

**Comment by atinesh-s** [comment]
> Quiz 11.pdf in week 6 contains 1,2,3 and 5 but no 4th question.

I have tried to add all questions but it might be possible that some questions are missed. Questions are also randomized so keep that in mind.

Feel free to reopen the issue if required.
