### ISSUE TITLE
Please Tell me how to fix this issue?

### ISSUE THREAD

**Issue by alok722** [atinesh-s/Coursera-Machine-Learning-Stanford#2]
>> gradientDescent
Not enough input arguments.

Error in gradientDescent (line 5)
m = length(y);

**Comment by atinesh-s** [comment]
Hello alok722 in which script you are getting error

**Comment by alok722** [comment]
I am sorry, the issue had been solved. Actually I was not running it properly. I was directly running the function instead of the whole exercise. Your code was perfect. Thanks.

**Comment by somrajmaji** [comment]
Hi 

Still getting the error in gradientDescent.m -

Error in gradientDescent (line 5)
m = length(y);

Do let me know how to run the code properly
