### ISSUE TITLE
About the course

### ISSUE THREAD

**Issue by rahul-sharma05** [atinesh-s/Coursera-Machine-Learning-Stanford#20]
Are some of the assignments in the course peer graded? And getting stuck if someone picks up a snippet or two would he be marked for plag?

**Comment by atinesh-s** [comment]
I am not sure if it will be marked as plagiarism if some portion of the code is taken

If you get stuck in some assignment then get the idea from the repository and write your own code

**Comment by rahul-sharma05** [comment]
Okay. Thanks!
