### ISSUE TITLE
For loop

### ISSUE THREAD

**Issue by Amethyst98** [atinesh-s/Coursera-Machine-Learning-Stanford#6]
Hey.... Thanks for everything you've been doing.... It really helps....... But I have a little issue.... It keeps telling me that there is a syntax error in the for loop

**Comment by atinesh-s** [comment]
Can you please specify the name of the script and programming assignment

**Comment by Amethyst98** [comment]
Week 5, programming assignment..... nnCostFunction

**Comment by atinesh-s** [comment]
Can you please specify the Line number in the code where you are facing the error

**Comment by Amethyst98** [comment]
The for loop....... Like so
For i = 1:m
     y_new(y(i), i) = 1;
endfor

**Comment by atinesh-s** [comment]
Try
```
for i=1:m
  y_new(y(i),i)=1;
end
```
instead of this
```
for i=1:m,
  y_new(y(i),i)=1;
end
```
and tell me if it solves the problem

**Comment by atinesh-s** [comment]
> The for loop....... Like so
> For i = 1:m
> y_new(y(i), i) = 1;
> endfor

Hello, Is your error resolved. If yes then please close the issue.
